title = "David Herbert"
baseURL = "https://david-dmh.github.io/David_Herbert/"
languageCode = "en-us"
theme = "ananke"
# themesDir = "../.."

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "G-D205NC0ZFV"
enableRobotsTXT = true
canonifyURLs = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "images/favicon0.ico"
  # Favicon attribution: https://www.flaticon.com/free-icons/data-processing - Data processing icons created by Eucalyp - Flaticon
  site_logo = ""
  description = ""
  facebook = ""
  #twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = "https://github.com/David-dmh"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/davidmherbert/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
  